services:
  - type: web
    name: calculator-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run init-db && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
    healthCheckPath: /health

databases:
  - name: calculator-postgres
    plan: free
    databaseName: calculator_db
    user: calculator_user
